In [2]:
from numba import njit
import numpy as np

In [3]:
def normal(size):
    strings = np.zeros(size)
    for i in range(size):
        strings[i] = 1 if i % 2 == 0 else 2
        
@njit()
def jit_normal(size):
    strings = np.zeros(size)
    for i in range(size):
        strings[i] = 1 if i % 2 == 0 else 2

In [4]:
%time normal(100000000)

Wall time: 14.1 s


In [5]:
%time jit_normal(100000000)

Wall time: 544 ms


In [7]:
print(np.zeros((10, 10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [12]:
directions = [
        (0, 1),
        (0, -1),
        (-1, 0),
        (1, 0)
    ]

In [13]:
for x, y in directions:
    print(x, y)

0 1
0 -1
-1 0
1 0


In [14]:
a = np.zeros(4)

In [15]:
print(a)

[0. 0. 0. 0.]


In [16]:
b = np.array([1, 1, 1, 1])
print(np.add(a, b))

[1. 1. 1. 1.]


In [17]:
print(a)

[0. 0. 0. 0.]


In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
from src.simulator.position import Position

In [2]:
a = Position(1, 1)
b = Position(1, 1)

print(a + b)


[2 2]
